name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create Directory Structure
        run: |
          mkdir -p dist
          mkdir -p dist/js
          mkdir -p dist/css
          mkdir -p dist/data

      - name: Create Firebase Config
        run: |
          mkdir -p js
          echo "import { initializeApp } from 'firebase/app';
          import { getDatabase, ref, get, update } from 'firebase/database';

          const firebaseConfig = {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
            databaseURL: '${{ secrets.FIREBASE_DATABASE_URL }}',
            projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
            storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.FIREBASE_APP_ID }}'
          };

          const app = initializeApp(firebaseConfig);
          const db = getDatabase(app);

          export { db };" > js/firebase.js

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy Static Files
        run: |
          cp index.html dist/
          cp about.html dist/ || echo "No about.html found"
          cp -r public/* dist/ || true
          cp -r css dist/ || true
          cp -r js dist/ || true
          cp -r assets dist/ || true
          cp -r images dist/ || true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true 