name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create Firebase Config
        run: |
          mkdir -p js
          echo "import { initializeApp } from 'firebase/app';
          import { getDatabase } from 'firebase/database';

          let db;
          try {
            const firebaseConfig = JSON.parse('${{ secrets.VITE_FIREBASE_CONFIG }}');
            const app = initializeApp(firebaseConfig);
            db = getDatabase(app);
          } catch (error) {
            console.error('Firebase initialization error:', error);
            db = {
              ref: () => ({}),
              get: async () => ({ val: () => null }),
              update: async () => {}
            };
          }

          export { db };" > js/firebase.js

      - name: Create Directory Structure
        run: |
          mkdir -p public/data
          mkdir -p dist

      - name: Copy Static Files
        run: |
          cp about.html dist/
          cp -r public/* dist/
          cp -r css dist/ || true
          cp -r js dist/
          cp -r assets dist/ || true
          cp -r images dist/ || true

      - name: Copy resources.json
        run: |
          echo '{
            "sources": [
              {
                "title": "SteamRip [SOFTWARE ONLY]",
                "description": "Smaller version of SteamRip that only includes software such as Lossless Scaling, Wallpaper...",
                "url": "https://hydralinks.cloud/sources/steamrip-software.json",
                "gamesCount": "7",
                "status": ["New", "Safe For Use"],
                "addedDate": "2024-03-18"
              }
            ]
          }' > public/data/resources.json

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true 